### PR TITLE
Configured artifact deployment to bintray. Resolved #18

### LINKED ISSUE #18: Setup deployment to public repository.

### PR DESCRIPTION
**Pull request by stlhrt**
No snapshots unfortunately.

### CODE REVIEW

**Comment by mariuszkumor** [comment]
@stlhrt do we need this integration in a case we want to go with the only one repository for DMN? And what with snapshots?

**Comment by stlhrt** [comment]
Of we go with single repo then integration for deployment will be needed
when we release

**Comment by mariuszkumor** [comment]
Exactly, however let's merge this pull request today. Once we hit the release day, we just only change the repo name to mvnrepository.

**Comment by stlhrt** [comment]
If you merge and we work on master then Travis will attempt to deploy to
bintray on every build

**Comment by mariuszkumor** [comment]
Ach... true. Let's hold this pull request till we decide to work on develop or master.

**Pull request closed without merging**
